/* KiloTNC - Developed by M6VPN (M6VPN@tuta.com) */
/* KiloTNC/embedded/targets/stm32h753-nucleo/target_resources.h */

#ifndef TARGET_RESOURCES_STM32H753_NUCLEO_H
#define TARGET_RESOURCES_STM32H753_NUCLEO_H

#define KILOTNC_STM32H753_RESOURCE_TARGET_NAME \
	"stm32h753-nucleo"

#define KILOTNC_STM32H753_USB_DEVICE_PLANNED		1
#define KILOTNC_STM32H753_TEST_PTT_GPIO_PLANNED		1
#define KILOTNC_STM32H753_AUDIO_SAI_PLANNED		1
#define KILOTNC_STM32H753_AUDIO_I2S_PLANNED		1
#define KILOTNC_STM32H753_DIAGNOSTIC_LED_PLANNED	1
#define KILOTNC_STM32H753_WATCHDOG_PLANNED		1
#define KILOTNC_STM32H753_RESET_CAUSE_PLANNED		1

/*
 * Pin assignments stay unverified in M2.11. Future firmware must verify
 * any real pin against ST documentation, the selected board schematic, and
 * a no-radio bench test before use.
 */
#define KILOTNC_STM32H753_PIN_ASSIGNMENTS_VERIFIED	0
#define KILOTNC_STM32H753_USB_PIN_ASSIGNMENTS_VERIFIED	0
#define KILOTNC_STM32H753_PTT_PIN_ASSIGNMENTS_VERIFIED	0
#define KILOTNC_STM32H753_AUDIO_PIN_ASSIGNMENTS_VERIFIED	0

#define KILOTNC_STM32H753_TEST_PTT_GPIO_PORT		"TBD"
#define KILOTNC_STM32H753_TEST_PTT_GPIO_PIN		"TBD"
#define KILOTNC_STM32H753_AUDIO_RESOURCE		"TBD"
#define KILOTNC_STM32H753_USB_RESOURCE			"TBD"

#endif
