/* KiloTNC - Developed by M6VPN (M6VPN@tuta.com) */
/* KiloTNC/embedded/targets/stm32h753-nucleo/target.h */

#ifndef TARGET_STM32H753_NUCLEO_H
#define TARGET_STM32H753_NUCLEO_H

#include "target_config.h"

#define KILOTNC_TARGET_NAME \
	KILOTNC_TARGET_STM32H753_NUCLEO_NAME
#define KILOTNC_TARGET_MCU_FAMILY \
	KILOTNC_TARGET_STM32H753_NUCLEO_MCU_FAMILY
#define KILOTNC_TARGET_BOARD_CLASS \
	KILOTNC_TARGET_STM32H753_NUCLEO_BOARD_CLASS

#define KILOTNC_TARGET_FEATURES \
	KILOTNC_TARGET_STM32H753_NUCLEO_FEATURES

#endif
