/* KiloTNC - Developed by M6VPN (M6VPN@tuta.com) */
/* KiloTNC/embedded/targets/stm32h753-nucleo/target.h */

#ifndef TARGET_STM32H753_NUCLEO_H
#define TARGET_STM32H753_NUCLEO_H

#include "kilotnc_board.h"

#define KILOTNC_TARGET_NAME		"stm32h753-nucleo"
#define KILOTNC_TARGET_MCU_FAMILY	"STM32H753"
#define KILOTNC_TARGET_BOARD_CLASS	"NUCLEO-H753ZI Nucleo-144"

#define KILOTNC_TARGET_FEATURES \
	(KILOTNC_BOARD_FEATURE_USB_DEVICE_PLANNED | \
	KILOTNC_BOARD_FEATURE_WATCHDOG_PLANNED | \
	KILOTNC_BOARD_FEATURE_SAI_I2S_PLANNED | \
	KILOTNC_BOARD_FEATURE_GPIO_TEST_PTT_PLANNED)

#endif
