/* KiloTNC - Developed by M6VPN (M6VPN@tuta.com) */
/* KiloTNC/firmware/include/kilotnc_limits.h */

#ifndef KILOTNC_LIMITS_H
#define KILOTNC_LIMITS_H

#include <sys/types.h>

#define KILOTNC_KISS_MAX_PAYLOAD	1024U
#define KILOTNC_KISS_MAX_FRAME		(KILOTNC_KISS_MAX_PAYLOAD + 1U)
#define KILOTNC_SETHW_MAX_PAYLOAD	64U

#define KILOTNC_AX25_MAX_CALLSIGN	6U
#define KILOTNC_AX25_MAX_DIGIS		8U
#define KILOTNC_AX25_ADDR_LEN		7U
#define KILOTNC_AX25_MIN_ADDRS		2U
#define KILOTNC_AX25_MAX_ADDRS \
	(KILOTNC_AX25_MIN_ADDRS + KILOTNC_AX25_MAX_DIGIS)
#define KILOTNC_AX25_MAX_INFO		256U
#define KILOTNC_AX25_MAX_FRAME_NO_FCS \
	((KILOTNC_AX25_MAX_ADDRS * KILOTNC_AX25_ADDR_LEN) + 2U + \
	KILOTNC_AX25_MAX_INFO)
#define KILOTNC_AX25_MAX_FRAME \
	(KILOTNC_AX25_MAX_FRAME_NO_FCS + 2U)

#define KILOTNC_HDLC_FLAG		0x7EU

#endif
