# KiloTNC - Developed by M6VPN (M6VPN@tuta.com)
# KiloTNC/daemon/example.conf

mode=NINO_MODE=6
profile=file-tx
kiss_in=build/daemon/input.kiss
pcm_out=build/daemon/config-tx.pcm
max_tx_ms=30000
p=255
slottime_10ms=10
fullduplex=0
