# KiloTNC - Developed by M6VPN (M6VPN@tuta.com)
# KiloTNC/daemon/examples/file-rx.conf

profile=file-rx
mode=NINO_MODE=6
pcm_in=build/daemon/input.pcm
kiss_out=build/daemon/example-file-rx.kiss
audio_backend=raw
audio_sample_rate=48000
audio_channels=1
audio_bits=16
radio_backend=none
max_tx_ms=30000
p=255
slottime_10ms=10
fullduplex=0
